import { Item } from "./item";


export let sample_items: Item[] = [
    
    {
        id: 0,
        path: 'assets/sofa/scene.gltf',
        name: 'sofa',
        image: '/assets/sofa.png',
        type: 'sofa',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 1,
        scaley: 1,
        scalez: 1,
    },
    {
        id: 1,
        path: 'assets/sofa_leather/scene.gltf',
        name: 'sofa leather',
        image: 'assets/sofa_leather.png',
        type: 'sofa',
        positionx: 0.65,
        positiony: 0.08,
        rotationz: -1.6,
        scalex: 1,
        scaley: 1,
        scalez: 1,

    },
    {
        id: 2,
        path: 'assets/sofa_3230/scene.gltf',
        name: 'sofa lounge',
        image: 'assets/sofa_3230.png',
        type: 'sofa',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 0.6,
        scaley: 0.6,
        scalez: 0.6,

    },
    {
        id: 3,
        path: 'assets/sofa_yellow/scene.gltf',
        name: 'sofayellow',
        image: 'assets/sofa_yellow.png',
        type: 'sofa',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: 3.1,
        scalex: 0.3,
        scaley: 0.4,
        scalez: 0.4,
  },
  {
    id: 4,
    path: 'assets/leather_chair/scene.gltf',
    name: 'yellow chair',
    image: 'assets/leather_chair.png',
    type: 'chair',
    positionx: 0.7,
    positiony: 0.155,
    rotationz: 0.1,
    scalex: 0.003,
    scaley: 0.004,
    scalez: 0.004,
},

{id: 5,
path: 'assets/red_chair/scene.gltf',
name: 'red chair',
image: 'assets/red_chair.png',
type: 'chair',
positionx: 0.7,
positiony: 0.255,
rotationz: -1.5,
scalex: 0.04,
scaley: 0.04,
scalez: 0.04,
},

{id: 6,
    path: 'assets/table_ronde/scene.gltf',
    name: 'table rond',
    image: 'assets/table_ronde.png',
    type: 'table',
    positionx: -0.3,
    positiony: 0.05,
   
    scalex: 0.005,
    scaley: 0.005,
    scalez: 0.005,
    },
{id: 7,
    path: 'assets/table_traditionnelle/scene.gltf',
    name: 'table traditionnelle',
    image: 'assets/table_tradionnelle.png',
    type: 'table',
    positionx: -0.3,
    positiony: 0.05,
   
    scalex: 0.4,
    scaley: 0.4,
    scalez: 0.4,
    },
{
        id: 8,
        path: 'assets/cofee_table/scene.gltf',
        name: 'coffee table',
        image: '/assets/coffe_table.png',
        type: 'table',
        positionx: -0.3,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 0.008,
        scaley: 0.009,
        scalez: 0.009,
    },
      
{id: 9,
    path: 'assets/wardrobe/scene.gltf',
    name: 'wardrobe',
    image: 'assets/wardrobe.png',
    type: 'cabinet',
    positionx: -1.6,
    positiony: 0.2,
    positionz: -1.4,
    rotationz: -1.5,
       
    scalex: 0.15,
    scaley: 0.35,
    scalez: 0.35,
    },
{id: 10,
    path: 'assets/colorful_wardrobe/scene.gltf',
    name: 'colorful wardrobe',
    image: 'assets/colorful_wardrobe.png',
    type: 'cabinet',
    positionx: -1.01,
    positiony: 1.2,
    positionz: 0.6,
    rotationz: 0,
       
    scalex: 0.0005,
    scaley: 0.0006,
    scalez: 0.0006,
    },
{id: 11,
    path: 'assets/aveiro_cabinet/scene.gltf',
    name: 'aveiro cabinet',
    image: 'assets/aveiro_cabinet.png',
    type: 'cabinet',
    positionx: -1.21,
    positiony: 1.2,
    positionz: 0.6,
    rotationz: 0,
       
    scalex: 0.007,
    scaley: 0.009,
    scalez: 0.009,
    },
{id: 12,
    path: 'assets/storage/scene.gltf',
    name: 'cabinet',
    image: 'assets/cabinet.jpg',
    type: 'storage',
    positionx: -0.4,
    positiony: 0,
    positionz: -1.295,
    rotationz: 0,
       
    scalex: 0.01,
    scaley: 0.01,
    scalez: 0.01,
    },
{id: 13,
    path: 'assets/deco_table/scene.gltf',
    name: 'deco table',
    image: 'assets/deco_table.png',
    type: 'storage',
    positionx: 2.5,
    positiony: 2.2,
    positionz: -1.295,
    rotationz: 0,
           
    scalex: 0.9,
    scaley: 0.9,
    scalez: 0.9,
     },
{id: 14,
    path: 'assets/low_shelving/scene.gltf',
    name: 'Fowler low shelving',
    image: 'assets/low_shelving.png',
    type: 'storage',
    positionx: 0.4,
    positiony: 1.8,
    positionz: 1.295,
    rotationz: 0,
           
    scalex: 0.006,
    scaley: 0.008,
    scalez: 0.008,
        },
{id: 15,
    path: 'assets/tv/scene.gltf',
    name: 'tv',
    image: 'assets/tv.png',
    type: 'accessory',
    positionx: -2.48,
    positiony: 0.8,
    positionz: -0.8,
    rotationz: -1.6,
           
    scalex: 0.01,
    scaley: 0.01,
    scalez: 0.01,
        },
{id: 16,
    path: 'assets/lamp/scene.gltf',
    name: 'Lamp',
    image: 'assets/lamp.png',
    type: 'accessory',
    positionx: 0.88,
    positiony: -0.3,
    positionz: -0.8,
    rotationz: -1.6,
           
    scalex: 0.01,
    scaley: 0.01,
    scalez: 0.01,
        }, 
{id: 17,
    path: 'assets/kameko_table/scene.gltf',
    name: 'Kameko side table',
    image: 'assets/kameko_table.png',
    type: 'accessory',
    positionx: 0,
    positiony: 0.3,
    positionz: -0.8,
    rotationz: -1.6,
           
    scalex: 0.01,
    scaley: 0.01,
    scalez: 0.01,
        }, 
{
        id: 18,
        path: 'assets/sofa/scene.gltf',
        name: 'delete the sofa',
        image: '/assets/annuler.png',
        type: 'sofa',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 0.0001,
        scaley: 0.0001,
        scalez: 0.0001,
    },
    {
        id: 19,
        path: 'assets/sofa/scene.gltf',
        name: 'delete the table',
        image: '/assets/annuler.png',
        type: 'table',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 0.0001,
        scaley: 0.0001,
        scalez: 0.0001,
    },
    {
        id: 20,
        path: 'assets/sofa/scene.gltf',
        name: 'delete the cabinet',
        image: '/assets/annuler.png',
        type: 'cabinet',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 0.0001,
        scaley: 0.0001,
        scalez: 0.0001,
    },
    {
        id: 21,
        path: 'assets/sofa/scene.gltf',
        name: 'delete the storage item',
        image: '/assets/annuler.png',
        type: 'storage',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 0.0001,
        scaley: 0.0001,
        scalez: 0.0001,
    },
    {
        id: 22,
        path: 'assets/sofa/scene.gltf',
        name: 'delete the accessory',
        image: '/assets/annuler.png',
        type: 'accessory',
        positionx: 0.7,
        positiony: 0.155,
        rotationz: -1.6,
        scalex: 0.0001,
        scaley: 0.0001,
        scalez: 0.0001,
    },
        
     
    
    
      
   
]